[package]
name = "colombo"
version = "0.1.0"
authors = ["Who"]
edition = "2018"
default-run = "colombo"

[dependencies]
cli = { package = "colombo-cli", path = "../../cli/colombo" }


[features]
runtime-benchmarks = ["cli/runtime-benchmarks"]
